### ISSUE TITLE
When I try to mod the game it keeps loading forever

### ISSUE THREAD

**Issue by ImmediateMurderProfessionals** [ozh/cookieclicker#76]
Why doesn't it work?

**Comment by ImmediateMurderProfessionals** [comment]
why did you close it without saying anything

**Comment by ozh** [comment]
Because I tend to quickly close useless issues.

1) it works, see http://ozh.github.io/cookieclicker/

2) this is a mirror of the original game hence there is no support for it, especially when users "mod" it (without giving any useful detail btw, which would be as useless if this repo was supporting issues of the game itself)

**Comment by ImmediateMurderProfessionals** [comment]
No like when I edit the code in a fork to add my own stuff, it doesn't work

**Comment by ImmediateMurderProfessionals** [comment]
(most of what i did was just change the messages in the news ticker and item descriptions to be funnier)
